apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
spec:
  template:
    spec:
      containers:
      - name: service-b
        image: service-b:1.0.0

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-b
data:
  db.url: http://database.production
  flavour: prio